version: "3"
services:
  app:
    container_name: clientesApi
    restart: always
    build: .
    ports:
      - "5000:3700"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb
    image: mongo
    ports: 
      - '27018:27017'
    logging:
      driver: none