version: "1"
services:
  web:
    container_name: clientesApi
    restart: always
    build: .
    ports:
      - "3700:3700"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      -"27017:27017"
    logging:
      drivers: none